Name:           perl-Math-Libm
Version:        1.00
Release:        2%{?dist}
Summary:        Perl extension for the C math library, libm
# The source doesn't include the license and author is unreachable
# File Changes says, this module was created using h2xs from /usr/include/math.h
# /usr/include/math.h is LGPLv2+ therefore, this module has to be LGPLv2+, right?
# In case this is a problem for Fedora, I should try to do the same steps as the author 12 years ago
License:        LGPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-Libm/
Source0:        http://www.cpan.org/authors/id/D/DS/DSLEWART/Math-Libm-%{version}.tar.gz
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(DynaLoader)
BuildRequires:  perl(AutoLoader)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       perl(Carp)
Requires:       perl(Exporter)
Requires:       perl(DynaLoader)
Requires:       perl(AutoLoader)

%{?perl_default_filter} # Filters (not)shared c libs

%description
This module is a translation of the C math.h file. It exports the following
selected constants and functions.

%prep
%setup -q -n Math-Libm-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Math*
%{_mandir}/man3/*

%changelog
* Sun Oct 07 2012 Miro Hrončok <miro@hroncok.cz> 1.00-3
- Rebuilding for 32bit, no spec changes.

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 1.00-2
- License issue solved, somehow.

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 1.00-1
- Specfile autogenerated by cpanspec 1.78 and revised.
