Name:           perl-Math-PlanePath
Version:        98
Release:        1%{?dist}
Summary:        Points on a path through the 2D plane
License:        GPLv3+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-PlanePath/
Source0:        http://www.cpan.org/authors/id/K/KR/KRYDE/Math-PlanePath-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl >= 0:5.004
BuildRequires:  perl(constant::defer) >= 5
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Math::BigFloat)
BuildRequires:  perl(Math::BigInt)
BuildRequires:  perl(Math::BigRat)
BuildRequires:  perl(Math::Libm)
Requires:       perl(constant::defer) >= 5
Requires:       perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))

# Filtering unversioned provides and requires
%global __provides_exclude %{?__provides_exclude:%__provides_exclude|}^perl\\(Math::PlanePath::CellularRule::OddSolid\\)$
%global __requires_exclude %{?__requires_exclude:%__requires_exclude|}^perl\\(constant::defer\\)$
%global __requires_exclude %{?__requires_exclude:%__requires_exclude|}^perl\\(constant\\)$

%description
This is a base class for some mathematical paths which map an integer
position $n to and from coordinates $x,$y in the 2D plane.

%prep
%setup -q -n Math-PlanePath-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
make pure_install DESTDIR=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc Changes COPYING
%{perl_vendorlib}/Math*
%{_mandir}/man3/*

%changelog
* Sat Feb 02 2013 Miro Hrončok <mhroncok@redhat.com> - 98-1
- New release
- Removed perl default filter
- %%{__perl} -> perl
- Replaced obsoleted PERL_INSTALL_ROOT with DESTDIR
- Removed deleting empty dirs
- Replaced BRs with BRs from Michal Ingeli <mi@v3.sk>
- Filter unversioned deps and provides

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 90-2
- Removed BRs provided by perl package

* Tue Oct 09 2012 Miro Hrončok <miro@hroncok.cz> 90-1
- New release

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 88-1
- Specfile autogenerated by cpanspec 1.78 adn revised.
