Name:           perl-Math-Clipper
Version:        1.14
Release:        1%{?dist}
Summary:        Polygon clipping in 2D
License:        Boost
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-Clipper/
Source0:        http://www.cpan.org/authors/id/A/AA/AAR/Math-Clipper-%{version}.tar.gz
BuildRequires:  perl(ExtUtils::Typemaps::Default) >= 0.05
BuildRequires:  perl(ExtUtils::XSpp) >= 0.16
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Build::WithXSpp)
BuildRequires:  perl(warnings)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Config)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(constant)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter} # Filters (not)shared c libs

%description
Clipper is a C++ (and Delphi) library that implements polygon clipping.

%prep
%setup -q -n Math-Clipper-%{version}
iconv -f iso8859-1 -t utf-8 src/clipper.cpp > src/clipper.cpp.conv && mv -f src/clipper.cpp.conv src/clipper.cpp
iconv -f iso8859-1 -t utf-8 src/clipper.hpp > src/clipper.hpp.conv && mv -f src/clipper.hpp.conv src/clipper.hpp
find src -name '*' -exec sed -i "s/\r//" {} \; 2>/dev/null

%build
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build
chmod -x src/clipper.*pp

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes META.json xsp
%doc src/clipper.*pp src/clipper.cpp src/*.h
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Math*
%{_mandir}/man3/*

%changelog
* Sun Oct 07 2012 Miro Hrončok <miro@hroncok.cz> 1.14-1
- New version.

* Sun Oct 07 2012 Miro Hrončok <miro@hroncok.cz> 1.09-2
- Rebuilding for 32bit, no spec changes.

* Thu Oct 04 2012 Miro Hrončok <miro@hroncok.cz> 1.09-1
- Specfile autogenerated by cpanspec 1.78 and revised.
