Name:           perl-ExtUtils-CppGuess
Version:        0.07
Release:        3%{?dist}
Summary:        Guess C++ compiler and flags
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/ExtUtils-CppGuess/
Source0:        http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-CppGuess-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Module::Build) >= 0.36
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Capture::Tiny)
BuildRequires:  perl(ExtUtils::Manifest)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(Cwd)
BuildRequires:  perl(Fatal)
BuildRequires:  perl(Exporter)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
ExtUtils::CppGuess attempts to guess the system's C++ compiler that is
compatible with the C compiler that your perl was built with.

%prep
%setup -q -n ExtUtils-CppGuess-%{version}

%build
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes README
#%%{perl_vendorlib}/auto/*
%{perl_vendorlib}/ExtUtils*
%{_mandir}/man3/*

%changelog
* Tue Dec 04 2012 Miro Hrončok <miro@hroncok.cz> - 0.07-3
- Removed deleting empty dirs
- Added BRs for t/lib/TestUtils.pm

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 0.07-2
- Removed useless BRs
- Removed perl autofilter

* Mon Oct 01 2012 Miro Hrončok <miro@hroncok.cz> 0.07-1
- Specfile autogenerated by cpanspec 1.78 and revised.
