Name:           perl-Module-Build-WithXSpp
Version:        0.11
Release:        1%{?dist}
Summary:        XS++ enhanced flavour of Module::Build
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Module-Build-WithXSpp/
Source0:        http://www.cpan.org/authors/id/S/SM/SMUELLER/Module-Build-WithXSpp-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(ExtUtils::CBuilder)
BuildRequires:  perl(ExtUtils::CppGuess) >= 0.04
BuildRequires:  perl(ExtUtils::ParseXS) >= 2.2205
BuildRequires:  perl(ExtUtils::Typemaps) >= 1.00
BuildRequires:  perl(ExtUtils::XSpp) >= 0.11
BuildRequires:  perl(Module::Build) >= 0.26
Requires:       perl(Digest::MD5)
Requires:       perl(ExtUtils::CBuilder)
Requires:       perl(ExtUtils::CppGuess) >= 0.04
Requires:       perl(ExtUtils::ParseXS) >= 2.2205
Requires:       perl(ExtUtils::Typemaps) >= 1.00
Requires:       perl(ExtUtils::XSpp) >= 0.11
Requires:       perl(Module::Build) >= 0.26
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This subclass of Module::Build adds some tools and processes to make it
easier to use for wrapping C++ using XS++ (ExtUtils::XSpp).

%prep
%setup -q -n Module-Build-WithXSpp-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Oct 01 2012 Miro Hrončok <miro@hroncok.cz> 0.11-1
- Specfile autogenerated by cpanspec 1.78 and revised.
