Name:           perl-Growl-GNTP
Version:        0.15
Release:        2%{?dist}
Summary:        Perl implementation of GNTP Protocol (Client Part)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Growl-GNTP/
Source0:        http://www.cpan.org/authors/id/M/MA/MATTN/Growl-GNTP-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Crypt::CBC) >= 2.29
BuildRequires:  perl(Data::UUID) >= 0.149
BuildRequires:  perl(Digest::MD5) >= 2.36
BuildRequires:  perl(Digest::SHA) >= 5.45
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Perl::Critic)
BuildRequires:  perl(inc::Module::Install)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(YAML)
BuildRequires:  perl(Test::Builder)
BuildRequires:  perl(Spiffy)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(LWP::Simple)
BuildRequires:  perl(Test::Builder)
BuildRequires:  perl(threads::shared)
BuildRequires:  perl(Module::Install::Base)
BuildRequires:  perl(Cwd)
BuildRequires:  perl(YAML::Tiny)
BuildRequires:  perl(ExtUtils::MM_Unix)
BuildRequires:  dos2unix
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Growl::GNTP is Perl implementation of GNTP Protocol (Client Part)

%prep
%setup -q -n Growl-GNTP-%{version}
dos2unix README

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 0.15-2
- Removed BRs provided by perl package
- Removed useless perl autofilter
- Using dos2unix

* Sat Sep 28 2012 Miro Hrončok <miro@hroncok.cz> 0.15-1
- Specfile autogenerated by cpanspec 1.78 and revised.
