Name:           perl-Growl-GNTP
Version:        0.16
Release:        1%{?dist}
Summary:        Perl implementation of GNTP Protocol (Client Part)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Growl-GNTP/
Source0:        http://www.cpan.org/authors/id/M/MA/MATTN/Growl-GNTP-%{version}.tar.gz
Patch0:         perl-Growl-GNTP-0.15-3.inc-and-xt-dereference.patch
BuildArch:      noarch
BuildRequires:  perl(Crypt::CBC) >= 2.29
BuildRequires:  perl(Data::UUID) >= 0.149
BuildRequires:  perl(Digest::MD5) >= 2.36
BuildRequires:  perl(Digest::SHA) >= 5.45
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Install)
BuildRequires:  perl(Test::More)
BuildRequires:  dos2unix
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Growl::GNTP is Perl implementation of GNTP Protocol (Client Part)

%prep
%setup -q -n Growl-GNTP-%{version}
%patch0 -p1
rm -rf inc xt
dos2unix README

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 11 2013 Miro Hrončok <mhroncok@redhat.com> - 0.16-1
- New version

* Tue Nov 20 2012 Miro Hrončok <miro@hroncok.cz> - 0.15-4
- perl(inc::Module::Install) to perl(Module::Install)

* Mon Nov 19 2012 Miro Hrončok <miro@hroncok.cz> - 0.15-3
- Removed local inc and xs directories
- Patched source so it doesn't need them
- Removed lots of BR (builds in mock)

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 0.15-2
- Removed BRs provided by perl package
- Removed useless perl autofilter
- Using dos2unix

* Sat Sep 28 2012 Miro Hrončok <miro@hroncok.cz> 0.15-1
- Specfile autogenerated by cpanspec 1.78 and revised.
