Name:           perl-Math-Clipper
Version:        1.16
Release:        1%{?dist}
Summary:        Perl wrapper around Clipper library
License:        Boost
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-Clipper/
Source0:        http://www.cpan.org/authors/id/A/AA/AAR/Math-Clipper-%{version}.tar.gz
BuildRequires:  perl(ExtUtils::Typemaps::Default) >= 0.05
BuildRequires:  perl(ExtUtils::XSpp) >= 0.16
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Build::WithXSpp)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Config)
BuildRequires:  perl(Exporter)
BuildRequires:  polyclipping-devel
BuildRequires:  dos2unix
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       libpolyclipping.so.3

%{?perl_default_filter} # Filters (not)shared c libs

%description
Perl module Math::Clipper is a wrapper around a Clipper library
that implements polygon clipping.

%prep
%setup -q -n Math-Clipper-%{version}
rm -f src/clipper.{c,h}pp
find src -name '*' -exec dos2unix {} \; 2>/dev/null
sed -i 's|clipper.hpp|polyclipping/clipper.hpp|' src/myinit.h

%build
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes META.json xsp
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Math*
%{_mandir}/man3/*

%changelog
* Fri Dec 28 2012 Miro Hrončok <miro@hroncok.cz> - 1.16-1
- New version
- Removed boundled C clipper and using the distribution one

* Mon Dec 17 2012 Miro Hrončok <miro@hroncok.cz> - 1.15-1
- New version
- Added perl(Config) and perl(Exporter) to BRs
- Removed deleting empty directories
- using dos2unix instead of sed

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 1.14-2
- Removed BRs provided by perl package

* Sun Oct 07 2012 Miro Hrončok <miro@hroncok.cz> 1.14-1
- New version.

* Sun Oct 07 2012 Miro Hrončok <miro@hroncok.cz> 1.09-2
- Rebuilding for 32bit, no spec changes.

* Thu Oct 04 2012 Miro Hrončok <miro@hroncok.cz> 1.09-1
- Specfile autogenerated by cpanspec 1.78 and revised.
