Name:           perl-Data-Rmap
Version:        0.62
Release:        3%{?dist}
Summary:        Recursive map, apply a block to a data structure
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Data-Rmap/
Source0:        http://www.cpan.org/authors/id/B/BO/BOWMANBS/Data-Rmap-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Exception)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Recursively evaluate a BLOCK over a list of data structures 
(locally setting $_ to each element) and return the list composed
of the results of such evaluations.  $_ can be used to modify
the elements.

%prep
%setup -q -n Data-Rmap-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test


%files
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 0.62-3
- Removed BRs provided by perl package and more

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 0.62-2
- Removed uselesss requires.

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 0.62-1
- Specfile autogenerated by cpanspec 1.78 and revised.
