Name:           perl-XML-SAX
Version:        0.99
Release:        10%{?dist}
Summary:        Simple API for XML
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-SAX/
Source0:        http://www.cpan.org/authors/id/G/GR/GRANTM/XML-SAX-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(XML::NamespaceSupport) >= 0.03
BuildRequires:  perl(XML::SAX::Base) >= 1.05
BuildRequires:  perl(Exporter)
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Symbol)
BuildRequires:  perl(constant)
BuildRequires:  perl(Test)
BuildRequires:  perl(warnings)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(Fatal)
BuildRequires:  perl(IO::File)
BuildRequires:  perl(XML::SAX::Exception)
BuildRequires:  perl(Carp)
Requires:       perl(XML::NamespaceSupport) >= 0.03
Requires:       perl(XML::SAX::Base) >= 1.05
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

# Otherwise I'll get E: useless-provides perl(XML::SAX::PurePerl)
%filter_from_provides /perl(XML::SAX::PurePerl) = %{version}/d
%filter_setup

%{?perl_default_filter} # Filters (not)shared c libs

%description
XML::SAX is a SAX parser access API for Perl. It includes classes and APIs
required for implementing SAX drivers, along with a factory class for
returning any SAX parser installed on the user's system.

%prep
%setup -q -n XML-SAX-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor << Y
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc Changes LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Oct 05 2012 Miro Hrončok <miro@hroncok.cz> 0.99-10
- Fake revision 10.

* Fri Oct 05 2012 Miro Hrončok <miro@hroncok.cz> 0.99-1
- Specfile autogenerated by cpanspec 1.78 and revised.
