Name:           perl-Language-Expr
Version:        0.19
Release:        3%{?dist}
Summary:        Simple mini-language for use in expression
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Language-Expr/
Source0:        http://www.cpan.org/authors/id/S/SH/SHARYANTO/Language-Expr-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl >= 0:5.010000
BuildRequires:  perl(boolean) >= 0.20
BuildRequires:  perl(Regexp::Grammars) >= 1.005
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Moo)
BuildRequires:  perl(UUID::Tiny)
BuildRequires:  perl(List::MoreUtils)
BuildRequires:  perl(Data::Clone)
BuildRequires:  perl(Data::Rmap)
BuildRequires:  perl(File::Which)
BuildRequires:  perl(String::ShellQuote)
BuildRequires:  perl(Test::Exception)
Requires:       perl(JSON)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Language::Expr defines a simple, Perl-like expression mini-language. It
supports mathematical and string operators, arrays, hashes, variables, and
functions. See Language::Expr::Manual::Syntax for description of the
language syntax.

%prep
%setup -q -n Language-Expr-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Nov 20 2012 Miro Hrončok <miro@hroncok.cz> - 0.19-3
- Removed some BRs
- Removed perl autofilter

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 0.19-2
- Removed BRs provided by perl package

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 0.19-1
- Specfile autogenerated by cpanspec 1.78 and revised.
