Name:           perl-Math-PlanePath
Version:        88
Release:        1%{?dist}
Summary:        Points on a path through the 2D plane
License:        GPLv3+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-PlanePath/
Source0:        http://www.cpan.org/authors/id/K/KR/KRYDE/Math-PlanePath-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl >= 0:5.004
BuildRequires:  perl(constant::defer) >= 5
BuildRequires:  perl(constant)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Math::Libm)
BuildRequires:  perl(Test)
BuildRequires:  perl(lib)
BuildRequires:  perl(Math::BigInt)
BuildRequires:  perl(Math::Prime::XS)
BuildRequires:  perl(Math::BigRat)
BuildRequires:  perl(Math::NumSeq::AllDigits)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(YAML)
BuildRequires:  perl(YAML::Syck)
BuildRequires:  perl(YAML::Tiny)
BuildRequires:  perl(YAML::XS)
BuildRequires:  perl(Parse::CPAN::Meta)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Module::Load)
BuildRequires:  perl(Math::BigFloat)
BuildRequires:  perl(Math::NumSeq)
BuildRequires:  perl(Math::NumSeq::Base::IterateIth)
BuildRequires:  perl(POSIX)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(Carp)
Requires:       perl(Math::NumSeq::Modulo)
Requires:       perl(File::Spec)
Requires:       perl(Module::Load)
Requires:       perl(Math::BigFloat)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter} # Filters (not)shared c libs

%description
This is a base class for some mathematical paths which map an integer
position $n to and from coordinates $x,$y in the 2D plane.

%prep
%setup -q -n Math-PlanePath-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes COPYING
#%%{perl_vendorlib}/auto/*
%{perl_vendorlib}/Math*
%{_mandir}/man3/*

%changelog
* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 88-1
- Specfile autogenerated by cpanspec 1.78 adn revised.
