Name:           perl-Regexp-Grammars
Version:        1.021
Release:        3%{?dist}
Summary:        Add grammatical parsing features to Perl 5.10 regexps
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Regexp-Grammars/
Source0:        http://www.cpan.org/authors/id/D/DC/DCONWAY/Regexp-Grammars-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(version)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module adds a small number of new regexp constructs that can be used
within Perl 5.10 patterns to implement complete recursive-descent parsing.

%prep
%setup -q -n Regexp-Grammars-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
./Build install destdir=%{buildroot} create_packlist=0

%{_fixperms} %{buildroot}/*

%check
./Build test

%files
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Dec 30 2012 Miro Hrončok <miro@hroncok.cz> - 1.021-3
- Removed the deleting empty directories
- Removed filter of shared libs, noarch
- Added BR perl(Data::Dumper)

* Fri Nov 16 2012 Miro Hrončok <miro@hroncok.cz> - 1.021-2
- Removed BRs provided by perl package

* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 1.021-1
- Specfile autogenerated by cpanspec 1.78 and revised.
