Name:           perl-Language-Expr
Version:        0.19
Release:        1%{?dist}
Summary:        Simple minilanguage for use in expression
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Language-Expr/
Source0:        http://www.cpan.org/authors/id/S/SH/SHARYANTO/Language-Expr-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl >= 0:5.010000
BuildRequires:  perl(boolean) >= 0.20
BuildRequires:  perl(Data::Clone)
BuildRequires:  perl(Data::Rmap)
BuildRequires:  perl(File::Which)
BuildRequires:  perl(JSON)
BuildRequires:  perl(List::MoreUtils)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moo)
BuildRequires:  perl(Regexp::Grammars) >= 1.005
BuildRequires:  perl(String::ShellQuote)
BuildRequires:  perl(UUID::Tiny)
Requires:       perl(boolean) >= 0.20
Requires:       perl(JSON)
Requires:       perl(List::MoreUtils)
Requires:       perl(Moo)
Requires:       perl(Regexp::Grammars) >= 1.005
Requires:       perl(UUID::Tiny)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter} # Filters (not)shared c libs

%description
Language::Expr defines a simple, Perl-like expression minilanguage. It
supports mathematical and string operators, arrays, hashes, variables, and
functions. See Language::Expr::Manual::Syntax for description of the
language syntax.

%prep
%setup -q -n Language-Expr-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Sep 23 2012 Miro Hrončok <miro@hroncok.cz> 0.19-1
- Specfile autogenerated by cpanspec 1.78.
